# Generated by Django 2.2.7 on 2019-11-17 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Game', max_length=200)),
                ('state', models.IntegerField(choices=[(0, 'new'), (1, 'playing'), (2, 'paused'), (3, 'won'), (4, 'lost')], default=0)),
                ('started', models.DateTimeField()),
                ('finished', models.DateTimeField(null=True)),
                ('rows', models.IntegerField(default=8)),
                ('cols', models.IntegerField(default=8)),
                ('mines', models.IntegerField(default=10)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('mine', models.BooleanField(default=False)),
                ('state', models.IntegerField(choices=[(0, 'hidden'), (1, 'question'), (2, 'flagged'), (3, 'uncovered')], default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='games.Game')),
            ],
        ),
    ]
