# Generated by Django 2.2.7 on 2019-11-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20191117_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='started',
            field=models.DateTimeField(null=True),
        ),
    ]
