# Generated by Django 2.2.7 on 2019-11-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20191117_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='uncovered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cell',
            name='state',
            field=models.IntegerField(choices=[(0, 'hidden'), (1, 'question'), (2, 'flagged'), (3, 'exploded')], default=0),
        ),
    ]
