# Generated by Django 2.2.7 on 2019-11-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20191117_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
